/* ObsNote.ts */

import { MarkdownView, Editor, TFile, getLinkpath } from 'obsidian';

import { HEADING_REGEX } from './constants';
import { ReplaceMode, NotePlaceholders } from './settings';

import xApp from './xApp';
import { getNoteEOL, sanitisedFileName, fileNamePrefix } from './xFile';
import { createOrAppendFile } from './xObsFile';
import FrontMatter from './FrontMatter';
import { replaceDateMask } from './xDateFns';

export default class ObsNote {
    private mdView: MarkdownView;
    public doc: Editor;
    private eol: string;
    private mdFile: TFile | null;
    private frontMatter: FrontMatter;
    private templatePlaceholders: NotePlaceholders;

    constructor() {
        const mdView = xApp.workspace.getActiveViewOfType(MarkdownView);
        if (mdView) {
            this.mdView = mdView;
            this.doc = mdView.editor;
            if(!this.doc) throw new Error('mdView.editor is null');
            const content = this.doc.getValue();
            this.eol = getNoteEOL(content);
            this.mdFile = mdView.file;
            this.frontMatter = new FrontMatter(this.eol, this.mdFile!, content);
            this.templatePlaceholders = new NotePlaceholders();
        } else {
            throw new Error('No current note selected ...');
        }
    }

    get frontmatter(): FrontMatter {
        return this.frontMatter;
    }

    getTopHeadingLevel(): void {
        //TODO - implementar isso para simplificar as opções de menu.
    }

    contentSplitByHeading(headingLevel: number): string[][] {
        const matches: string[][] = [];
        if (!this.doc) return matches;

        const content = this.doc.getValue().split(this.eol);
        const parentHeading = new Array(headingLevel).join('#') + ' ';
        const heading = new Array(headingLevel + 1).join('#') + ' ';
        let headingMatch: string[] = [];
        content.forEach((line, i) => {
            if (line.startsWith(heading)) {
                if (headingMatch.length > 0) {
                    matches.push(headingMatch);
                    headingMatch = [];
                    headingMatch.push(line);
                } else {
                    headingMatch.push(line);
                }
            } else if (headingMatch.length > 0 && !line.startsWith(parentHeading)) {
                headingMatch.push(line);
            } else if (headingMatch.length > 0) {
                matches.push(headingMatch);
                headingMatch = [];
            }
            //Making sure the last headingMatch array is added to the matches
            if (i === content.length - 1 && headingMatch.length > 0) {
                matches.push(headingMatch);
            }
        });
        return matches;
    }

    async createNoteWithFirstLineAsFileName(dedupedHeader: string, selectedContent: string[], mode: ReplaceMode, isMultiple: boolean) {
        const [originalHeader, ...contentArr] = selectedContent;

        //TODO -> working here ...

        const fileName = sanitisedFileName(dedupedHeader);
        const originalNote = this.noteContent(originalHeader, contentArr);
        let note = originalNote;
        const filePath = await createOrAppendFile(fileName, '');

        if (xApp.settings.refactoredNoteTemplate !== undefined && xApp.settings.refactoredNoteTemplate !== '') {
            const link = await xApp.fileManager.generateMarkdownLink(this.mdView.file!, '', '', '');
            const newNoteLink = await this.markdownLink(filePath!);
            note = this.templatedContent(note, xApp.settings.refactoredNoteTemplate, this.mdView.file!.basename, link, fileName, newNoteLink, '', note);
        }
        await createOrAppendFile(fileName, note);
        //TODO: update frontmatter into the new note.

        await this.replaceContent(fileName, filePath!, this.mdView.file!, note, originalNote, mode);
        // TODO: updateOriginChildren?
        if (!isMultiple && xApp.settings.openNewNote) {
            await xApp.workspace.openLinkText(fileName, getLinkpath(filePath!), true);
        }
    }

    async createAutogeneratedNote(selectedContent: string[], mode: ReplaceMode, isMultiple: boolean) {
        const [header, ...contentArr] = selectedContent;

        const fileName = fileNamePrefix(); // Only prefix is used for the note file name
        const originalNote = this.noteContent(header, contentArr);
        let note = originalNote;
        const filePath = await createOrAppendFile(fileName, '');

        if (xApp.settings.refactoredNoteTemplate !== undefined && xApp.settings.refactoredNoteTemplate !== '') {
            const link = await xApp.fileManager.generateMarkdownLink(this.mdView.file!, '', '', '');
            const newNoteLink = await this.markdownLink(filePath!);
            note = this.templatedContent(note, xApp.settings.refactoredNoteTemplate, this.mdView.file!.basename, link, fileName, newNoteLink, '', note);
        }

        await createOrAppendFile(fileName, note);
        await this.replaceContent(fileName, filePath!, this.mdView.file!, note, originalNote, mode);
        // TODO: updateOriginChildren?
        if (!isMultiple) {
            await xApp.workspace.openLinkText(fileName, getLinkpath(filePath!), true);
        }
    }

    noteRemainder(): string[] {
        //content below or above?
        const doc = this.doc;
        doc.setCursor(doc.getCursor().line, 0);
        const currentLine = doc.getCursor();
        const endPosition = doc.offsetToPos(doc.getValue().length);
        const content = doc.getRange(currentLine, endPosition);
        const trimmedContent = content.trim();
        return trimmedContent.split(this.eol);
    }

    selectedContent(): string[] {
        const doc = this.doc;
        const selectedText = doc.getSelection()
        const trimmedContent = selectedText.trim();
        return trimmedContent.split(this.eol)
    }

    // ------------------------------------------------------------------------------------------------------

    removeNoteRemainder(text: string): void {
        const doc = this.doc;
        const currentLine = doc.getCursor();
        const endPosition = doc.offsetToPos(doc.getValue().length);
        doc.replaceRange(text, currentLine, endPosition);
    }

    async replaceContent(fileName: string, filePath: string, currentNote: TFile, content: string, originalContent: string, mode: ReplaceMode): Promise<void> {
        const transclude = xApp.settings.transcludeByDefault ? '!' : '';
        const link = await this.markdownLink(filePath);
        const currentNoteLink = await this.markdownLink(currentNote.path);
        let contentToInsert = transclude + link;

        contentToInsert = this.templatedContent(contentToInsert, xApp.settings.noteLinkTemplate, currentNote.basename, currentNoteLink, fileName, link, '', content);

        const doc = this.doc;
        if (mode === 'split') {
            this.removeNoteRemainder(contentToInsert);
        } else if (mode === 'replace-selection') {
            doc.replaceSelection(contentToInsert);
        } else if (mode === 'replace-headings') {
            doc.setValue(doc.getValue().replace(originalContent, contentToInsert));
        }
    }

    async markdownLink(filePath: string) {
        const file = await xApp.vault.getMarkdownFiles().filter(f => f.path === filePath)[0];
        const link = await xApp.fileManager.generateMarkdownLink(file, '', '', '');
        return link;
    }

    templatedContent(input: string, template: string, currentNoteTitle: string, currentNoteLink: string, newNoteTitle: string, newNoteLink: string, newNotePath: string, newNoteContent: string): string {
        if (template === undefined || template === '') {
            return input;
        }
        let output = template;
        output = replaceDateMask(output);
        output = this.templatePlaceholders.title.replace(output, currentNoteTitle);
        output = this.templatePlaceholders.link.replace(output, currentNoteLink);
        output = this.templatePlaceholders.newNoteTitle.replace(output, newNoteTitle);
        output = this.templatePlaceholders.newNoteLink.replace(output, newNoteLink);
        output = this.templatePlaceholders.newNoteContent.replace(output, newNoteContent);
        output = this.templatePlaceholders.newNotePath.replace(output, newNotePath);
        //TODO: create new placeholders - frontmatter, newNoteFrontmatter
        return output;
    }

    // ------------------------------------------------------------------------------------------------------

    noteContent(firstLine: string, contentArr: string[], contentOnly?: boolean): string {
        if (xApp.settings.includeFirstLineAsNoteHeading) {
            //Replaces any non-word characters whitespace leading the first line to enforce consistent heading format from setting
            const headingBaseline = firstLine.replace(HEADING_REGEX, '');
            //Adds formatted heading into content array as first item. 
            //Trimming allows for an empty heading format. 
            contentArr.unshift(`${xApp.settings.headingFormat} ${headingBaseline}`.trim());
        } else if (!xApp.settings.excludeFirstLineInNote || contentOnly) {
            //Adds first line back into content if it is not to be included as a header or if the command is content only
            contentArr.unshift(firstLine);
        }
        if (xApp.settings.normalizeHeaderLevels) {
            contentArr = this.normalizeHeadingLevels(contentArr);
        }
        return contentArr.join(this.eol).trim();
    }

    headingLevel(line: string): number {
        let headingLevel = 0;
        for (let i = 0; i < line.length; i++) {
            if (line[i] === '#') {
                headingLevel++;
            } else if (line[i] === ' ') {
                break;
            } else {
                headingLevel = 0;
                break;
            }
        }
        return headingLevel;
    }

    normalizeHeadingLevels(contentArr: string[]): string[] {
        const minHeadingLevel = Math.min(...contentArr.map(line => this.headingLevel(line)).filter(level => level > 0));
        if (minHeadingLevel > 1) {
            contentArr.forEach((line, i) => {
                const level = this.headingLevel(line);
                if (level > 0) {
                    contentArr[i] = line.substr(minHeadingLevel - 1);
                }
            });
        }
        return contentArr;
    }

}

/* EOF*/